### ISSUE TITLE
End of October test state

### ISSUE THREAD

**Issue by Mirv** [Mirv/basicb#123]
47 runs, 40 assertions, 0 failures, 12 errors, 0 skips

**Comment by Mirv** [comment]
- [ ] Solved?

  1) Error:
CountriesControllerTest#test_should_update_country:
NoMethodError: undefined method `player_id' for #<Country:0x000000087f70a8>
Did you mean?  player_ids
               player_ids=
               playercountry_ids
               players
               playercountry_ids=
               players=
    test/controllers/countries_controller_test.rb:41:in `block in <class:CountriesControllerTest>'

**Comment by Mirv** [comment]
- [ ] Solved?

  1) Error:
CountriesControllerTest#test_should_update_country:
NoMethodError: undefined method `player_id' for #<Country:0x00000003edb388>
Did you mean?  player_ids
               player_ids=
               playercountry_ids
               players
               playercountry_ids=
               players=
    test/controllers/countries_controller_test.rb:42:in `block in <class:CountriesControllerTest>'
