### ISSUE TITLE
Campaign#Index#New > CampaignRegistration#create

### ISSUE THREAD

**Issue by Mirv** [Mirv/basicb#124]
Need to make guard clauses to locate error `undefined method 'count' for NilClass:Class` in the `enroller` class
```
Application Trace | Framework Trace | Full Trace
app/classes/Enroller.rb:167:in `row_count_obj'
app/classes/Enroller.rb:120:in `ComposeName'
app/classes/Enroller.rb:90:in `create_campaign_player'
app/classes/Enroller.rb:65:in `setup_in_campaign'
app/classes/Enroller.rb:42:in `enrolling'
app/controllers/campaign_registrations_controller.rb:58:in `create'
```

**Comment by Mirv** [comment]
Resolved by commit https://github.com/Mirv/basicb/commit/650336f13270b65fb15d41e33c893a8f2e01d018
