### ISSUE TITLE
Rails - dependency issues? Two probably same issue

### ISSUE THREAD

**Issue by Mirv** [Mirv/basicb#89]
Two errors of the same type
```
Error:
CountriesControllerTest#test_should_destroy_country:
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "countries" violates foreign key constraint "fk_rails_e12f24b98f" on table "dashcounts"
DETAIL:  Key (id)=(980190962) is still referenced from table "dashcounts".
: DELETE FROM "countries" WHERE "countries"."id" = $1
    app/controllers/countries_controller.rb:58:in `destroy'
    test/controllers/countries_controller_test.rb:47:in `block (2 levels) in <class:CountriesControllerTest>'
    test/controllers/countries_controller_test.rb:46:in `block in <class:CountriesControllerTest>'


bin/rails test test/controllers/countries_controller_test.rb:45

E..............E

Error:
PlayersControllerTest#test_should_destroy_player:
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "players" violates foreign key constraint "fk_rails_6d0e0987de" on table "playercountries"
DETAIL:  Key (id)=(980190962) is still referenced from table "playercountries".
: DELETE FROM "players" WHERE "players"."id" = $1
    app/controllers/players_controller.rb:72:in `destroy'
    test/controllers/players_controller_test.rb:66:in `block (2 levels) in <class:PlayersControllerTest>'
    test/controllers/players_controller_test.rb:65:in `block in <class:PlayersControllerTest>'
```

**Comment by Mirv** [comment]
Originally I put down `dependent: :destroy` after all the `has_many` & `has_many: :through`.

The fix was that I only need it on the `has_many` of the two real tables, not the join tables & not the `has_many: :through` tables.
